export default Object.freeze({
  JOBS_DETAILS: "Jobs Details",
  JOBS_FAVORITE: "Jobs Favorite",
  PRO_RESUME: "Resume",
  PRO_RESUME_BASIC: "Basic Info",
  PRO_RESUME_PERSONAL: "Personal Info",
  PRO_DONE: "Done",
  PRO_SKILL: "Skill",
  PRO_SKILL_UPDATE: "Skill Update",
  PRO_LANGUAGE: "Language",
  PRO_LANGUAGE_UPDATE: "Language Update",
  PRO_EDUCATION: "Education",
  PRO_EDUCATION_UPDATE: "Education Update",
  PRO_EXPERIENCE: "Experience",
  PRO_EXPERIENCE_UPDATE: "Experience Update",
  PRO_PERSONAL_DETAILS: "Personal Details",
  PRO_JOB_PREFERENCES: "Job Preferences",
  PRO_TRAINING: "Training",
  PRO_TRAINING_EDIT: "Training Update",
  PRO_PHOTO_UPLOAD: "Photo Upload",
  AC_MESAGES: "Messages",
  AC_MESAGES_VIEW: "Message View",
  PRO_JOB_DONE: "Job Apply",
  JOB_List: "Jobs",
  JOB_FAV_LIST: "Favorite Jobs",
  JOB_APL_LIST: "Jobs Applied",
  AUTH_PASSWORD_RESET: "Password Reset",
  AUTH_PASSWORD_RESET_SAVE: "Password Reset Save",
  AUTH_LOGIN: "Login",

  RETSET_DONE: "Reset Done",
});
